name: CI

on: [push, pull_request]

jobs:
  build:
    name: My Job
    runs-on: ubuntu-18.04
    container:
      image: ubuntu:18.04
    steps:
    - uses: actions/checkout@v2
    - name: apt update
      run: apt-get update
    - name: Install base packages
      run: |
        apt-get install --yes \
        gpg \
        make \
        net-tools \
        software-properties-common
    - name: Fix da shit
      run: echo "127.0.0.1 `cat /etc/hostname`" >> /etc/hosts
    - name: Debug
      run: env && cat /etc/hosts && cat /etc/resolv.conf && ifconfig
    - name: Add OPC UA ppa
      run: add-apt-repository ppa:open62541-team/ppa && apt-get update
    - name: Install Perl Modules for Testng and libopen62541
      run: |
        apt-get install --yes \
        libdevel-checklib-perl \
        libopen62541-1 \
        libopen62541-1-dev \
        libopen62541-1-tools \
        libtest-deep-perl \
        libtest-exception-perl \
        libtest-leaktrace-perl \
        libtest-nowarnings-perl \
        libtest-pod-perl \
        libtest-requires-perl \
        libtest-tcp-perl \
        libtest-warn-perl
    - name: perl Makefile
      run: perl Makefile.PL
    - name: Make
      run: make
    - name: Test client-connect-async.t
      run: make && perl -I blib/lib/ -I blib/arch/ t/client-connect-async.t TEST_VERBOSITY=1
    - name: Test all
      run: make test
